### ISSUE TITLE
criu check shows error from vagrant machine!

### ISSUE THREAD

**Issue by rowshan** [checkpoint-restore/criu#496]
Hi I get following error : 

`vagrant@vagrant-ubuntu-trusty-64:~/criu$ sudo criu check`
`Warn  (criu/kerndat.c:792): Can't load /run/criu.kdat
Error (criu/sockets.c:136): Diag module missing (-2)
Error (criu/sockets.c:136): Diag module missing (-2)
Error (criu/sockets.c:136): Diag module missing (-2)
Warn  (criu/net.c:2770): Unable to get socket network namespace
Warn  (criu/net.c:2770): Unable to get tun network namespace
Warn  (criu/sk-unix.c:214): sk unix: Unable to open a socket file: Bad address
Warn  (criu/libnetlink.c:55): ERROR -95 reported by netlink
Error (criu/kerndat.c:645): NSID is not supported`   

Please advice me how to solve this error. Thanks in advance!

**Comment by rst0git** [comment]
Hi @rowshan 
Try to install the `linux-image-extra` package for your kernel version

     apt-get install -y linux-image-extra-`uname -r`

**Comment by rowshan** [comment]
Hi @rst0git
I tired to install it but still the  same error. 
`vagrant@vagrant-ubuntu-trusty-64:~/criu$ sudo apt-get install -y linux-image-extra-`uname -r`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-image-extra-3.13.0-149-generic is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
`
`vagrant@vagrant-ubuntu-trusty-64:~/criu$ sudo criu check
Warn  (criu/kerndat.c:792): Can't load /run/criu.kdat
Warn  (criu/net.c:2770): Unable to get socket network namespace
Warn  (criu/net.c:2770): Unable to get tun network namespace
Warn  (criu/sk-unix.c:214): sk unix: Unable to open a socket file: Bad address
Warn  (criu/libnetlink.c:55): ERROR -95 reported by netlink
Error (criu/kerndat.c:645): NSID is not supported
`

**Comment by rppt** [comment]
Hi @rowshan 

3.13 is really old kernel. I'd suggest upgrading the kernel. You can also try using more recent Ubuntu version than trusty.

**Comment by rst0git** [comment]
@rppt I agree that v3.13 is an old kernel, but according to the [Custom kernel](https://criu.org/Custom_kernel) page CRIU should work with Linux above v3.11. Do we need to update this page?

@rowshan I was able to reproduce your problem with `3.13.0-149-generic` and I can confirm that this problem does not exist in newer versions of Ubuntu (such as 16.04).

**Comment by rowshan** [comment]
Hello! thanks, It was very helpful. I updated the kernel and rebooted the machine and then everything is working  properly.

**Comment by planetA** [comment]
I also have an error:

> Warn  (criu/kerndat.c:792): Can't load /run/criu.kdat
> Error (criu/sockets.c:136): Diag module missing (-2)
> Error (criu/sockets.c:136): Diag module missing (-2)
> Error (criu/sockets.c:136): Diag module missing (-2)
> Error (criu/util.c:803): exited, status=3
> Error (criu/util.c:803): exited, status=3
> Error (criu/tun.c:82): Unable to create tun: No such file or directory

I have a self compiled 4.16.13 kernel. 

I have "CONFIG_CHECKPOINT_RESTORE=y", but seemingly it is not enough.

Would else do I need to enable in the kernel to get criu support and what linux-image-extra is expected to do?

**Comment by rst0git** [comment]
Hi @planetA 

The message `Error (criu/sockets.c:136): Diag module missing (-2)` indicates that diag modules are missing (see commit 4857d0c ).

Try to enable the sock-diag options from https://criu.org/Linux_kernel

**Comment by planetA** [comment]
@rst0git Problem with diag went away, but /run/criu.kdat is still missing:

> $ criu check
> Warn  (criu/kerndat.c:792): Can't load /run/criu.kdat
> Error (criu/util.c:803): exited, status=1
> Error (criu/util.c:803): exited, status=1
> Warn  (criu/net.c:2770): Unable to get socket network namespace
> Error (criu/tun.c:82): Unable to create tun: No such file or directory

I have all necessary flags now set. And I cannot find what exactly creates this file.

**Comment by rst0git** [comment]
Hi @planetA 

The `/run/criu.kdat` is a temporary file used to cache collected kerndat. (For more info see commit 07a0066 or the wiki page https://criu.org/Kerndat).

You need to run criu as root to be able to read/write to this file. It has the following permissions:
```
-rw------- 1 root root 752 Jun  3 14:40 /run/criu.kdat
```

Would you be able to add `CONFIG_TUN` to the wiki page?

**Comment by planetA** [comment]
@rst0git I would need to request an account for that

**Comment by rst0git** [comment]
No problem, I added it.
@planetA feel free to request an account for the wiki and update the documentation when needed.

**Comment by 0x7f454c46** [comment]
I think, CONFIG_TUN is optional and criu should work without it.
We have kerndat, which fails if there is no tun device..
Something like this should fix it in criu:
```
diff --git a/criu/tun.c b/criu/tun.c
index 8274ccb8d71b..c1dabaf37d96 100644
--- a/criu/tun.c
+++ b/criu/tun.c
@@ -74,17 +74,18 @@ int check_tun_cr(int no_tun_err)
 
 int check_tun_netns_cr(bool *result)
 {
-       bool val;
+       bool val = false;
        int tun;
 
        tun = open(TUN_DEV_GEN_PATH, O_RDONLY);
        if (tun < 0) {
                pr_perror("Unable to create tun");
-               return -1;
+               goto out;
        }
        check_has_netns_ioc(tun, &val, "tun");
        close(tun);
 
+out:
        if (result)
                *result = val;
 
```

**Comment by planetA** [comment]
@0x7f454c46 CONFIG_IP_NF_IPTABLES also may be useful. I needed it to restore an application using network.
