### ISSUE TITLE
[x32] sigpending.c:75: The signal is received before unlocking (errno = 2 (No such file or directory))

### ISSUE THREAD

**Issue by avagin** [checkpoint-restore/criu#666]
```
======================= Run zdtm/static/sigpending in h ========================
Start test
./sigpending --pidfile=sigpending.pid --outfile=sigpending.out
Run criu dump
Run criu restore
Send the 15 signal to  49
Wait for zdtm/static/sigpending(49) to die for 0.100000
############### Test zdtm/static/sigpending FAIL at result check ###############
Test output: ================================
15:00:15.012:    49: signo=64 si_code=fffffff6
15:00:15.012:    49: ERR: sigpending.c:75: The signal is received before unlocking (errno = 2 (No such file or directory))
15:00:15.012:    49: signo=64 si_code=fffffff5
15:00:15.012:    49: ERR: sigpending.c:75: The signal is received before unlocking (errno = 2 (No such file or directory))
15:00:15.012:    49: signo=17 si_code=1
15:00:15.012:    49: ERR: sigpending.c:75: The signal is received before unlocking (errno = 2 (No such file or directory))
15:00:15.014:    49: signo=34 si_code=fffffff4
15:00:15.014:    49: signo=34 si_code=fffffff3
15:00:15.014:    49: signo=34 si_code=fffffff2
15:00:15.014:    49: signo=34 si_code=fffffff1
15:00:15.014:    49: signo=34 si_code=fffffff0
15:00:15.014:    49: signo=34 si_code=ffffffef
15:00:15.014:    49: signo=34 si_code=ffffffee
15:00:15.014:    49: signo=34 si_code=ffffffed
15:00:15.014:    49: signo=34 si_code=ffffffec
15:00:15.014:    49: signo=34 si_code=ffffffeb
15:00:15.014:    49: signo=34 si_code=ffffffea
15:00:15.014:    49: signo=34 si_code=ffffffe9
15:00:15.014:    49: signo=34 si_code=ffffffe8
15:00:15.014:    49: signo=34 si_code=ffffffe7
15:00:15.014:    49: signo=34 si_code=ffffffe6
15:00:15.014:    49: signo=34 si_code=ffffffe5
15:00:15.014:    49: signo=34 si_code=ffffffe4
15:00:15.014:    49: signo=34 si_code=ffffffe3
15:00:15.014:    49: signo=34 si_code=ffffffe2
15:00:15.014:    49: signo=34 si_code=ffffffe1
15:00:15.014:    49: signo=34 si_code=ffffffe0
15:00:15.014:    49: signo=34 si_code=ffffffdf
15:00:15.014:    49: signo=34 si_code=ffffffde
15:00:15.014:    49: signo=34 si_code=ffffffdd
15:00:15.014:    49: signo=34 si_code=ffffffdc
15:00:15.014:    49: signo=34 si_code=ffffffdb
15:00:15.014:    49: signo=34 si_code=ffffffda
15:00:15.015:    49: signo=34 si_code=ffffffd9
15:00:15.015:    49: signo=34 si_code=ffffffd8
15:00:15.015:    49: signo=34 si_code=ffffffd7
15:00:15.015:    49: signo=34 si_code=ffffffd6
15:00:15.015:    49: signo=34 si_code=ffffffd5
15:00:15.015:    49: signo=34 si_code=ffffffd4
15:00:15.015:    49: signo=34 si_code=ffffffd3
15:00:15.015:    49: signo=34 si_code=ffffffd2
15:00:15.015:    49: signo=34 si_code=ffffffd1
15:00:15.015:    49: signo=34 si_code=ffffffd0
15:00:15.015:    49: signo=34 si_code=ffffffcf
15:00:15.015:    49: signo=34 si_code=ffffffce
15:00:15.015:    49: signo=34 si_code=ffffffcd
15:00:15.015:    49: signo=34 si_code=ffffffcc
15:00:15.015:    49: signo=34 si_code=ffffffcb
15:00:15.015:    49: signo=34 si_code=ffffffca
15:00:15.015:    49: signo=34 si_code=ffffffc9
15:00:15.015:    49: signo=34 si_code=ffffffc8
15:00:15.015:    49: signo=34 si_code=ffffffc7
15:00:15.015:    49: signo=34 si_code=ffffffc6
15:00:15.015:    49: signo=34 si_code=ffffffc5
15:00:15.015:    49: signo=34 si_code=ffffffc4
15:00:15.015:    49: signo=34 si_code=ffffffc3
15:00:15.015:    49: signo=34 si_code=ffffffc2
15:00:15.015:    49: signo=34 si_code=ffffffc1
15:00:15.015:    49: signo=34 si_code=ffffffc0
15:00:15.015:    49: signo=34 si_code=ffffffbf
15:00:15.015:    49: signo=34 si_code=ffffffbe
15:00:15.015:    49: signo=34 si_code=ffffffbd
15:00:15.015:    49: signo=34 si_code=ffffffbc
15:00:15.015:    49: signo=34 si_code=ffffffbb
15:00:15.015:    49: signo=34 si_code=ffffffba
15:00:15.015:    49: signo=34 si_code=ffffffb9
15:00:15.015:    49: signo=34 si_code=ffffffb8
15:00:15.015:    49: signo=34 si_code=ffffffb7
15:00:15.015:    49: signo=34 si_code=ffffffb6
15:00:15.015:    49: signo=34 si_code=ffffffb5
15:00:15.015:    49: signo=34 si_code=ffffffb4
15:00:15.015:    49: signo=34 si_code=ffffffb3
15:00:15.015:    49: signo=34 si_code=ffffffb2
15:00:15.015:    49: FAIL: sigpending.c:172: The signal blocking mask was changed (errno = 0 (Success))
15:00:15.015:    49: FAIL: sigpending.c:298: The signal blocking mask was changed (errno = 11 (Resource temporarily unavailable))

 <<< ================================
```
https://ci.openvz.org/job/CRIU/job/CRIU-x86-32/job/criu-dev/1924/consoleFull

**Comment by avagin** [comment]
70e06765af4614330205628cde0a49e30535f303 is the first bad commit
commit 70e06765af4614330205628cde0a49e30535f303
Author: Adrian Reber <areber@redhat.com>
Date:   Wed Mar 13 12:48:19 2019 +0000

    criu: fix gcc9 rawhide compilation errors
    
    Signed-off-by: Adrian Reber <areber@redhat.com>

:040000 040000 cb4426e6f5ce41f6ab39a3b5137c31fb37c5cff1 15236e97a340283d1213dab45a4ba1a6b68d0504 M	compel
:040000 040000 4f06a0f12237cd24c8b79580bfc254805b4cdac1 d386e8c9cb5ef99a2e027c658008dc57a3f107e0 M	criu

**Comment by avagin** [comment]
Steps to reproduce:
bash-4.4# git clean -dxf test/
bash-4.4# export COMPAT_TEST=y
bash-4.4# python test/zdtm.py run -t zdtm/static/sigpending

**Comment by avagin** [comment]
The problem here is that we restore SigBlk masks incorrectly:

Before C/R:
SigBlk:	fffffffe7ffbbeff
SigBlk:	fffffffe7ffbbeff

After C/R:
SigBlk:	7ffbbeff00000000
SigBlk:	7ffbbeff00000000

**Comment by avagin** [comment]
Before 70e0676:
(gdb) p &((struct ucontext_ia32 *)0)->uc_sigmask
$1 = (k_rtsigset_t *) 0x6c

After 70e0676:
(gdb) p &((struct ucontext_ia32 *)0)->uc_sigmask
$1 = (k_rtsigset_t *) 0x70

**Comment by 0x7f454c46** [comment]
Hehe, as expected: https://github.com/checkpoint-restore/criu/pull/649#issuecomment-472496186
I'll look at that. I guess, related to removing __packed attributes.
I've also noticed that Travis-CI has 4.15 these days, so I'm planning to add an env for ia32 to prevent further such happenings. Actually, I even had some draft for that - but found that on ubuntu there are some problems to install both 64/32 bit .so - so, was trying to find not disgusting way to hack it around.

**Comment by adrianreber** [comment]
@0x7f454c46 : thanks!
